site_name: Footprint Documentation
site_url: https://unparallel-innovation.github.io/Footprint-Documentation/
site_description: Footprint Documentation
site_author: Unparallel Innovation, Lda

nav:
- Introduction: index.md
- Assembly / Connection:
    - Flashing the SD Card: flashing.md
    - Connection Guide: connection.md
    - Internet Connection: internet_connection.md
    - Access Point: access_point.md
- Dashboard:
    - Home: dashboard/dashboard.md
    - Wi-Fi: dashboard/wifi.md
    - VPN: dashboard/vpn.md
    - MQTT: dashboard/mqtt.md
    - System: dashboard/system.md

theme:
    name: material
    features:
        - navigation.sections

markdown_extensions:
    - attr_list
    - md_in_html
    - toc:
        toc_depth: 0

copyright: Copyright &copy; 2021 <a href="https://www.unparallel.pt">UNPARALLEL Innovation, Lda</a>.
