# Build Documentation using MkDocs

name: CI

# Controls when the workflow will run
on:
  push:
    # Only run this job for tags with a valid version
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  EXP: '^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Set env
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/*/} | sed -n -E "s/$EXP/\1.\2.\3/p")" >> $GITHUB_ENV
      - run: pip install mkdocs-material mike
      - run: mike deploy --push --update-aliases ${{ env.VERSION }} latest
