# Build Documentation using MkDocs

name: CI

# Controls when the workflow will run
on:
  push:
    # Only run this job for tags with a valid version
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  EXP: '^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs-material mike
      - name: Set version
        run: echo "VERSION=$(echo $GITHUB_REF_NAME | sed -n -E "s/$EXP/\1.\2.\3/p")" >> $GITHUB_ENV
      - name: Config git
        run: |
          git config --global user.name ci-bot
          git config --global user.email cicd@unparallel.pt
          git fetch origin gh-pages --depth=1
      - name: Deploy
        run: |
          mike deploy --push --update-aliases ${{ env.VERSION }} latest
          mike set-default --push latest
